<?php

/**
 * Created by PhpStorm.
 * User: yangchunrun
 * Date: 16/7/9
 * Time: 上午11:32
 */
namespace app\user\components;
use app\home\components\BaseController;
class AuthController extends BaseController
{

    public function beforeAction($action)
    {


        if (\Yii::$app->user->isGuest) {

            $this->redirect(['/#signin']);
        }


        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}