<?php

/**
 * Created by PhpStorm.
 * User: yangchunrun
 * Date: 16/5/3
 * Time: 上午10:19
 */
namespace app\source;
class Module extends  \yii\base\Model
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}