<?php
/**
 * Created by PhpStorm.
 * User: yangchunrun
 * Date: 16/7/9
 * Time: 上午11:37
 */

namespace app\user\controllers;


use app\user\components\AuthController;
use app\user\models\User;

class MineController extends AuthController
{
    public $_username;
    public $_user;


    public function beforeAction($action)
    {
        $this->_username = \Yii::$app->request->get('username');

        if ($this->_username) {
            $this->_user = User::find()->where(['username' => $this->_username])->one();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionActivity()
    {
        return $this->render('activity');
    }


    public function actionPreferences(){
        return $this->render('preferences',['user'=>$this->_user]);
    }

}