<?php
/**
 * Created by PhpStorm.
 * User: yangchunrun
 * Date: 16/4/29
 * Time: 下午1:43
 */

namespace app\admin\components;


use app\admin\models\AdminAcl;
use app\admin\models\AdminGroupAcl;
use yii\base\ActionFilter;

class AclFilter extends  ActionFilter
{


    public function afterAction($action, $result)
    {

        $module = $this->owner->module->id;
        $controller = $this->owner->id;
        $actionId = $action->id;
        if(\Yii::$app->adminUser->isGuest&&strtolower($actionId)!='login'){

            $this->owner->redirect(['/login']);
        }else {
            if (!in_array(1, $this->owner->group_id)) {
                $aclCheck = $this->checkAcl($module, $controller, $actionId, \Yii::$app->adminUser->identity->group_id);

                if (!$aclCheck) {
                    return $this->owner->render('@app/admin/views/layouts/ban');
                }
            }
        }
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    //页面权限检测显示
    public function showAcl($controller, $action)
    {
        $aclCheck = $this->checkAcl($controller, $action, \Yii::$app->adminUser->identity->group_id);
        return $aclCheck;
    }

    //检查权限
    public function checkAcl($module,$controller, $action, $group_id)
    {
        $groupAclModel = new AdminGroupAcl();
        $aclModel = new AdminAcl();
        $myAcl = $groupAclModel->find()->select('acl_ids')->where(['group_id'=>$group_id])->asArray()->all();
        $acl_ids='';
        foreach($myAcl as $key=>$val){
            $acl_ids.= $val['acl_ids'].',';
        }
        $acl_ids=substr($acl_ids,0,-1);
        $acl_array = array_unique(explode(',', $acl_ids));
        $row = $aclModel->find()->where(['lower(module)'=>strtolower($module)])->where(['lower(controller)'=>strtolower($controller)])
            ->andWhere(['lower(action)'=>strtolower($action)])->asArray()->one();
        if (!empty($acl_array) && !in_array($row['id'], $acl_array)&&$row) {
            return false;
        }

        return true;
    }
}